spring:
  application:
    name: TicketProvider
  redis:
    host: 192.168.9.130
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 2

server:
  port: 8763


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/